
package com.rvho.cxfclient.wsdl.cxf.hello;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-15T14:09:42.341+08:00
 * Generated source version: 3.1.5
 * 
 */
public final class HelloWS_HelloWSPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.tmp.com/services/hello", "HelloWSService");

    private HelloWS_HelloWSPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWSService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWSService ss = new HelloWSService(wsdlURL, SERVICE_NAME);
        HelloWS port = ss.getHelloWSPort();  
        
        {
        System.out.println("Invoking welcome...");
        java.lang.String _welcome_name = "";
        java.lang.String _welcome__return = port.welcome(_welcome_name);
        System.out.println("welcome.result=" + _welcome__return);


        }

        System.exit(0);
    }

}
