package com.rvho.cxfclient.wsdl.cxf.hello;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.5
 * 2016-02-15T14:09:42.404+08:00
 * Generated source version: 3.1.5
 * 
 */
@WebService(targetNamespace = "http://www.tmp.com/services/hello", name = "HelloWS")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWS {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "welcome", targetNamespace = "http://www.tmp.com/services/hello", className = "com.rvho.cxfclient.wsdl.cxf.hello.Welcome")
    @WebMethod
    @ResponseWrapper(localName = "welcomeResponse", targetNamespace = "http://www.tmp.com/services/hello", className = "com.rvho.cxfclient.wsdl.cxf.hello.WelcomeResponse")
    public java.lang.String welcome(
        @WebParam(name = "name", targetNamespace = "")
        java.lang.String name
    );
}
